spring.application.name=ezzyhub-backend
# Server Configuration
server.port=8080



# Increase max file upload size (for large repos)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Logging
logging.level.com.ezzyhub=DEBUG
logging.level.org.springframework=INFO

# Banner
spring.main.banner-mode=console